import Loading from "@/components/Loading";
import ProductsTable from "@/components/ProductsTable";
import Head from "next/head";
import { useQuery, useQueryClient } from "react-query";
import { QUERY_KEY_PRODUCTS } from "../helper/data-fetch/constant";
import { getProducts } from "../helper/data-fetch/controller";

export default function Home() {
  const { isLoading, isError, error, data } = useQuery(
    QUERY_KEY_PRODUCTS,
    getProducts,
    {
      retry: false
    }
  );

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-[85vh]">
        <Loading size={10} />
      </div>
    );
  }

  if (isError) {
    return <div className="mt-4 font-bold text-red-500">Error: {error.message}</div>;
  }

  return (
    <>
      <Head>
        <title>Grocery Store Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductsTable data={data} />
    </>
  );
}
